# .goreleaser.yml
# Build customization
builds:
  - binary: herd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
checksum:
  # You can change the name of the checksums file.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"
